---
manager_gui_group: "artifacts-tomcat-manager-gui"
manager_script_group: "artifacts-tomcat-manager-script"
manager_jmx_group: "artifacts-tomcat-manager-jmx"
manager_status_group: "artifacts-tomcat-manager-status"
admin_gui_group: "artifacts-tomcat-admin-gui"
admin_script_group: "artifacts-tomcat-admin-script"
admin_jmx_group: "artifacts-tomcat-admin-jmx"
admin_status_group: "artifacts-tomcat-admin-status"
artifactory_derby_version: 10.11.1.1
artifactory_derby_jar: "derby-{{ artifactory_derby_version }}.jar"
artifactory_war: artifactory.war
artifactory_deploy_war: "{{ tomcat_webapps_dir }}/{{ artifactory_war }}"
artifactory_xml_file: "artifactory.xml"
artifactory_xml_template: "{{ artifactory_xml_file }}.j2"
artifactory_xml: "{{ tomcat_localhost_conf_dir }}/{{ artifactory_xml_file }}"

