---
manager_gui_group: "jenkins-manager-gui"
manager_script_group: "jenkins-manager-script"
manager_jmx_group: "jenkins-manager-jmx"
manager_status_group: "jenkins-manager-status"
admin_gui_group: "jenkins-admin-gui"
admin_script_group: "jenkins-admin-script"
admin_jmx_group: "jenkins-admin-jmx"
admin_status_group: "jenkins-admin-status"