---
rc_conf: /etc/rc.conf
krb5_conf: /etc/krb5.conf
pam_dir: /etc/pam.d
keytabs_dir: /etc/keytabs
nonexistent_home: /nonexistent
nologin_class: /usr/sbin/nologin
local_config_dir: /usr/local/etc
local_libexec_dir: /usr/local/libexec
local_rc_dir: "{{ local_config_dir }}/rc.d"
fontconfig_dir: "{{ local_config_dir }}/fonts"
ssl_dir: "/etc/ssl"
ssl_certs_dir: "{{ ssl_dir }}/certs"
ssl_keys_dir: "{{ ssl_dir }}/private"
ssl_crl_dir: "{{ ssl_dir }}/crl"
ssl_ca_cert: "{{ ssl_certs_dir}}/ca-cert.pem"
ssl_ca_crl: "{{ ssl_crl_dir }}/crl.pem"
ldap_config_dir: "{{ local_config_dir }}/openldap"
ldap_config_file: "{{ ldap_config_dir }}/ldap.conf"
ldap_client_cert_filename: "{{ ansible_hostname }}-ldap-cert.pem"
ldap_client_cert: "{{ ssl_certs_dir }}/{{ ldap_client_cert_filename }}"
ldap_client_key_filename: "{{ ansible_hostname }}-ldap-key.pem"
ldap_client_key: "{{ ssl_keys_dir }}/{{ ldap_client_key_filename }}"
nslcd_config: "{{ local_config_dir }}/nslcd.conf"
nslcd_cert_filename: "{{ ansible_hostname }}-nss-cert.pem"
nslcd_cert: "{{ ssl_certs_dir }}/{{ nslcd_cert_filename }}"
nslcd_key_filename: "{{ ansible_hostname }}-nss-key.pem"
nslcd_key: "{{ ssl_keys_dir }}/{{ nslcd_key_filename }}"
nslcd_keytab: "{{ keytabs_dir }}/nss.keytab"
nslcd_user: nslcd
nslcd_group: nslcd
slapd_user: ldap
slapd_group: ldap
slapd_run: /var/run/openldap
slapd_data: /var/db/openldap-data
sasl_conf_dir: "/usr/local/lib/sasl2"
sasl_mux: /var/run/saslauthd/mux
sasl_group: mail
postgres_user: pgsql
postgres_group: pgsql
postgres_data: /var/db/pgsql
postgres_home: /usr/local/pgsql
tor_config_dir: "{{ local_config_dir }}/tor"
tor_data_dir: /var/db/tor
tor_group: _tor
tor_user: _tor
privoxy_group: privoxy
privoxy_user: privoxy
privoxy_config_dir: "{{ local_config_dir }}/privoxy"
privoxy_doc_dir: "/usr/local/share/doc/privoxy"
squid_group: squid
squid_user: squid
squid_config_dir: "{{ local_config_dir }}/squid"
squid_data: /var/squid
letsencrypt_cert_filename: "letsencrypt-cert.pem"
letsencrypt_cert: "{{ ssl_certs_dir }}/{{ letsencrypt_cert_filename }}"
letsencrypt_key_filename: "letsencrypt-key.pem"
letsencrypt_key: "{{ ssl_keys_dir }}/{{ letsencrypt_key_filename }}"
dovecot_group: dovecot
dovecot_user: dovecot
dovecot_login_group: dovenull
dovecot_login_user: dovenull
dovecot_ldap_cert_filename: "{{ ansible_hostname }}-dovecot-ldap-cert.pem"
dovecot_ldap_cert: "{{ ssl_certs_dir }}/{{ dovecot_ldap_cert_filename }}"
dovecot_ldap_key_filename: "{{ ansible_hostname }}-dovecot-ldap-key.pem"
dovecot_ldap_key: "{{ ssl_keys_dir }}/{{ dovecot_ldap_key_filename }}"
dovecot_mail_cert: "{{ ssl_certs_dir }}/imap-cert.pem"
dovecot_mail_key: "{{ ssl_keys_dir }}/imap-key.pem"
dovecot_config_dir: "{{ local_config_dir }}/dovecot"
dovecot_config: "{{ dovecot_config_dir }}/dovecot.conf"
dovecot_ldap_config: "{{ dovecot_config_dir }}/dovecot-ldap.conf"
dovecot_run_dir: /var/run/dovecot
dovecot_auth_socket: /var/spool/postfix/private/auth
dovecot_keytab: "{{ keytabs_dir }}/dovecot.keytab"
maia_group: vscan
maia_user: vscan
maia_database_user: maia
maia_homedir: /var/maiad
maia_config_dir: "{{ local_config_dir }}/maia"
maia_postgres_cert_filename: "{{ ansible_hostname }}-postgres-cert.pem"
maia_postgres_cert: "{{ ssl_certs_dir }}/{{ maia_postgres_cert_filename }}"
maia_postgres_key_filename: "{{ ansible_hostname }}-postgres-key.pem"
maia_postgres_key: "{{ ssl_certs_dir }}/{{ maia_postgres_key_filename }}"
maia_salearn: "/usr/local/bin/sa-learn"
maia_local_cf_dir: "{{ local_config_dir }}/mail/spamassassin"
maia_rules_dir: "/var/db/spamassassin"
maia_scripts_dir: "/usr/local/share/maia/scripts"
maia_run_dir: "/var/run/maia"
maia_log_dir: "/var/log/maia"
maia_keytab: "{{ keytabs_dir }}/maia.keytab"
www_group: www
www_user: www
www_cert: "{{ ssl_certs_dir }}/https-cert.pem"
www_key: "{{ ssl_keys_dir }}/https-key.pem"
www_virtual_host_dir: /var/www
www_keytab: "{{ keytabs_dir }}/apache.keytab"
www_config_dir: "{{ local_config_dir }}/apache24"
www_config: "{{ www_config_dir }}/httpd.conf"
www_prefix: "/usr/local"
postfix_group: postfix
postfix_user: postfix
sendmail_bin: /usr/local/bin/sendmail
nsswitch_conf: "/etc/nsswitch.conf"
empty_dir: "/var/empty"
kinit: /usr/bin/kinit
ansible_python_interpreter: /usr/local/bin/python
ansible_become_method: su
