---
rc_conf: /etc/rc.conf
krb5_conf: /etc/krb5.conf
pam_dir: /etc/pam.d
keytabs_dir: /etc/keytabs
nonexistent_home: /nonexistent
nologin_class: /usr/sbin/nologin
local_dir: /usr/local
local_config_dir: "{{ local_dir }}/etc"
local_sbin_dir: "{{ local_dir }}/sbin"
local_libexec_dir: "{{ local_dir }}/libexec"
local_share_dir: "{{ local_dir }}/share"
local_rc_dir: "{{ local_config_dir }}/rc.d"
local_jars_dir: "{{ local_share_dir }}/java/classes"
fontconfig_dir: "{{ local_config_dir }}/fonts"
ssl_dir: /etc/ssl
ssl_certs_dir: "{{ ssl_dir }}/certs"
ssl_keys_dir: "{{ ssl_dir }}/private"
ssl_keystores_dir: "{{ ssl_dir }}/keystores"
ssl_crl_dir: "{{ ssl_dir }}/crl"
ssl_ca_cert: "{{ ssl_certs_dir}}/ca-cert.pem"
ssl_ca_crl: "{{ ssl_crl_dir }}/crl.pem"
ssl_ca_keystore_file: "ca.keystore"
ssl_ca_keystore: "{{ ssl_keystores_dir }}/{{ ssl_ca_keystore_file }}"
ssl_ca_keystore_password: "changeit"
mail_group: mail
ldap_config_dir: "{{ local_config_dir }}/openldap"
ldap_config_file: "{{ ldap_config_dir }}/ldap.conf"
ldap_client_cert_filename: "{{ ansible_hostname }}-ldap-cert.pem"
ldap_client_cert: "{{ ssl_certs_dir }}/{{ ldap_client_cert_filename }}"
ldap_client_key_filename: "{{ ansible_hostname }}-ldap-key.pem"
ldap_client_key: "{{ ssl_keys_dir }}/{{ ldap_client_key_filename }}"
nslcd_config: "{{ local_config_dir }}/nslcd.conf"
nslcd_cert_filename: "{{ ansible_hostname }}-nss-cert.pem"
nslcd_cert: "{{ ssl_certs_dir }}/{{ nslcd_cert_filename }}"
nslcd_key_filename: "{{ ansible_hostname }}-nss-key.pem"
nslcd_key: "{{ ssl_keys_dir }}/{{ nslcd_key_filename }}"
nslcd_keytab: "{{ keytabs_dir }}/nss.keytab"
nslcd_user: nslcd
nslcd_group: nslcd
slapd_user: ldap
slapd_group: ldap
slapd_run: /var/run/openldap
slapd_data: /var/db/openldap-data
sasl_conf_dir: "/usr/local/lib/sasl2"
sasl_mux: /var/run/saslauthd/mux
sasl_group: "{{ mail_group }}"
postgres_user: pgsql
postgres_group: pgsql
postgres_data: /var/db/pgsql
postgres_home: /usr/local/pgsql
postgres_jar: "postgresql.jar"
postgres_jar_install: "{{ local_jars_dir }}/{{ postgres_jar }}"
tor_config_dir: "{{ local_config_dir }}/tor"
tor_data_dir: /var/db/tor
tor_group: _tor
tor_user: _tor
privoxy_group: privoxy
privoxy_user: privoxy
privoxy_config_dir: "{{ local_config_dir }}/privoxy"
privoxy_doc_dir: "/usr/local/share/doc/privoxy"
squid_group: squid
squid_user: squid
squid_config_dir: "{{ local_config_dir }}/squid"
squid_data: /var/squid
squid_cert_filename: "{{ ansible_hostname }}-squid-cert.pem"
squid_cert: "{{ ssl_certs_dir }}/{{ squid_cert_filename }}"
squid_key_filename: "{{ ansible_hostname }}-squid-key.pem"
squid_key: "{{ ssl_keys_dir }}/{{ squid_key_filename }}"
letsencrypt_www_cert_filename: "www.{{ network_name }}-cert.pem"
letsencrypt_www_cert: "{{ ssl_certs_dir }}/{{ letsencrypt_www_cert_filename }}"
letsencrypt_www_key_filename: "www.{{ network_name }}-key.pem"
letsencrypt_www_key: "{{ ssl_keys_dir }}/{{ letsencrypt_www_key_filename }}"
letsencrypt_mail_cert_filename: "mail.{{ network_name }}-cert.pem"
letsencrypt_mail_cert: "{{ ssl_certs_dir }}/{{ letsencrypt_mail_cert_filename }}"
letsencrypt_mail_key_filename: "mail.{{ network_name }}-key.pem"
letsencrypt_mail_key: "{{ ssl_keys_dir }}/{{ letsencrypt_mail_key_filename }}"
dovecot_group: dovecot
dovecot_user: dovecot
dovecot_login_group: dovenull
dovecot_login_user: dovenull
dovecot_ldap_cert_filename: "{{ ansible_hostname }}-dovecot-ldap-cert.pem"
dovecot_ldap_cert: "{{ ssl_certs_dir }}/{{ dovecot_ldap_cert_filename }}"
dovecot_ldap_key_filename: "{{ ansible_hostname }}-dovecot-ldap-key.pem"
dovecot_ldap_key: "{{ ssl_keys_dir }}/{{ dovecot_ldap_key_filename }}"
dovecot_mail_cert: "{{ ssl_certs_dir }}/imap-cert.pem"
dovecot_mail_key: "{{ ssl_keys_dir }}/imap-key.pem"
dovecot_config_dir: "{{ local_config_dir }}/dovecot"
dovecot_config: "{{ dovecot_config_dir }}/dovecot.conf"
dovecot_ldap_config: "{{ dovecot_config_dir }}/dovecot-ldap.conf"
dovecot_run_dir: /var/run/dovecot
dovecot_auth_socket: /var/spool/postfix/private/auth
dovecot_keytab: "{{ keytabs_dir }}/dovecot.keytab"
dovecot_libexec_dir: "{{ local_libexec_dir }}/dovecot"
maia_group: vscan
maia_user: vscan
maia_database_user: maia
maia_homedir: /var/maiad
maia_config_dir: "{{ local_config_dir }}/maia"
maia_postgres_cert_filename: "{{ ansible_hostname }}-maia-postgres-cert.pem"
maia_postgres_cert: "{{ ssl_certs_dir }}/{{ maia_postgres_cert_filename }}"
maia_postgres_key_filename: "{{ ansible_hostname }}-maia-postgres-key.pem"
maia_postgres_key: "{{ ssl_certs_dir }}/{{ maia_postgres_key_filename }}"
maia_salearn: "/usr/local/bin/sa-learn"
maia_local_cf_dir: "{{ local_config_dir }}/mail/spamassassin"
maia_rules_dir: "/var/db/spamassassin"
maia_scripts_dir: "/usr/local/share/maia/scripts"
maia_run_dir: "/var/run/maia"
maia_log_dir: "/var/log/maia"
maia_keytab: "{{ keytabs_dir }}/maia.keytab"
clamav_group: clamav
clamav_user: clamav
www_group: www
www_user: www
www_cert: "{{ ssl_certs_dir }}/https-cert.pem"
www_key: "{{ ssl_keys_dir }}/https-key.pem"
www_virtual_host_dir: /var/www
www_network_virtual_host_dir: "{{ www_virtual_host_dir }}/{{ network_name }}"
www_ca_info_dir: "{{ www_network_virtual_host_dir }}/ca"
www_keytab: "{{ keytabs_dir }}/apache.keytab"
www_config_dir: "{{ local_config_dir }}/apache24"
www_config: "{{ www_config_dir }}/httpd.conf"
www_workers_properties: "{{ www_config_dir }}/workers.properties"
www_prefix: "/usr/local"
postfix_group: postfix
postfix_user: postfix
postfix_ldap_cert_filename: "{{ ansible_hostname }}-postfix-ldap-cert.pem"
postfix_ldap_cert: "{{ ssl_certs_dir }}/{{ postfix_ldap_cert_filename }}"
postfix_ldap_key_filename: "{{ ansible_hostname }}-postfix-ldap-key.pem"
postfix_ldap_key: "{{ ssl_keys_dir }}/{{ postfix_ldap_key_filename }}"
postfix_mail_cert: "{{ ssl_certs_dir }}/smtp-cert.pem"
postfix_mail_key: "{{ ssl_keys_dir }}/smtp-key.pem"
postfix_config_dir: "{{ local_config_dir }}/postfix"
postfix_daemon_dir: "{{ local_libexec_dir }}/postfix"
postfix_queue_dir: /var/spool/postfix
postfix_data_dir: /var/db/postfix
postfix_keytab: "{{ keytabs_dir }}/postfix.keytab"
postfix_master_config: "{{ postfix_config_dir }}/master.cf"
postfix_main_config: "{{ postfix_config_dir }}/main.cf"
postfix_ldap_config: "{{ postfix_config_dir }}/postfix-ldap.cf"
mailer_config: "/etc/mail/mailer.conf"
sendmail_bin: /usr/local/sbin/sendmail
nsswitch_conf: "/etc/nsswitch.conf"
empty_dir: "/var/empty"
tomcat_base_dir: "/usr/local/apache-tomcat-8.0"
tomcat_user: www
tomcat_group: www
tomcat_uid: 80
tomcat_gid: 80
tomcat_principal: "tomcat/{{ ansible_fqdn }}@{{ kerberos_realm }}"
tomcat_lib_dir: "{{ tomcat_base_dir }}/lib"
artifactory_dir: "{{ local_dir }}/artifactory"
artifactory_install_war: "{{ artifactory_dir }}/webapps/{{ artifactory_war }}"
artifactory_install_tomcat: "{{ artifactory_dir }}/tomcat/"
artifactory_install_tomcat_lib: "{{ artifactory_install_tomcat }}/lib"
artifactory_install_derby_jar: "{{ artifactory_install_tomcat_lib }}/{{ artifactory_derby_jar }}"
artifactory_deploy_derby_jar: "{{ tomcat_lib_dir }}/{{ artifactory_derby_jar }}"
artifactory_user: "{{ tomcat_user }}"
artifactory_home: "/var/artifactory"
artifactory_etc: "{{ artifactory_home }}/etc"
artifactory_db_properties_file: "db.properties"
artifactory_db_properties_template: "{{ artifactory_db_properties_file }}.j2"
artifactory_db_properties: "{{ artifactory_etc }}/{{ artifactory_db_properties_file }}"
access_home: "{{ artifactory_home }}/access"
access_etc: "{{ access_home }}/etc"
access_db_properties_file: "db.properties"
access_db_properties_template: "{{ access_db_properties_file }}.j2"
access_db_properties: "{{ access_etc }}/{{ access_db_properties_file }}"
openjdk_dir: /usr/local/openjdk8
openjdk_cacerts_keystore: "{{ openjdk_dir }}/jre/lib/security/cacerts"
openssl_ciphers: "ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA"
jenkins_war_file: "jenkins.war"
jenkins_war_install: "{{ local_share_dir }}/jenkins/{{ jenkins_war_file }}"
jenkins_home: "/var/run/jenkins"
kinit: /usr/bin/kinit
ansible_python_interpreter: /usr/local/bin/python
ansible_become_method: su
