---
rc_conf: /etc/rc.conf
krb5_conf: /etc/krb5.conf
pam_dir: /etc/pam.d
local_config_dir: /usr/local/etc
local_rc_dir: "{{ local_config_dir }}/rc.d"
fontconfig_dir: "{{ local_config_dir }}/fonts"
network_name: metricspace.net
kerberos_realm: METRICSPACE.NET
primary_kdc: kdc.metricspace.net
ansible_python_interpreter: /usr/local/bin/python
