---
rc_conf: /etc/rc.conf
krb5_conf: /etc/krb5.conf
pam_dir: /etc/pam.d
local_config_dir: /usr/local/etc
local_rc_dir: "{{ local_config_dir }}/rc.d"
fontconfig_dir: "{{ local_config_dir }}/fonts"
ssl_dir: "/etc/ssl"
ssl_certs_dir: "{{ ssl_dir }}/certs"
ssl_keys_dir: "{{ ssl_dir }}/private"
ssl_crl_dir: "{{ ssl_dir }}/crl"
ssl_ca_cert: "{{ ssl_certs_dir}}/ca-cert.pem"
ssl_ca_crl: "{{ ssl_crl_dir }}/crl.pem"
ldap_config_dir: "{{ local_config_dir }}/openldap"
ldap_config_file: "{{ ldap_config_dir }}/ldap.conf"
ldap_client_cert_filename: "{{ ansible_hostname }}-ldap-cert.pem"
ldap_client_cert: "{{ ssl_certs_dir }}/{{ ldap_client_cert_filename }}"
ldap_client_key_filename: "{{ ansible_hostname }}-ldap-key.pem"
ldap_client_key: "{{ ssl_keys_dir }}/{{ ldap_client_key_filename }}"
nlscd_config: "{{ local_config_dir }}/nslcd.conf"
nslcd_cert_filename: "{{ ansible_hostname }}-nss-cert.pem"
nslcd_cert: "{{ ssl_certs_dir }}/{{ nslcd_cert_filename }}"
nslcd_key_filename: "{{ ansible_hostname }}-nss-key.pem"
nslcd_key: "{{ ssl_certs_dir }}/{{ nslcd_key_filename }}"
nsswitch_conf: "/etc/nsswitch.conf"
ansible_python_interpreter: /usr/local/bin/python
ansible_become_method: su
