---
ansible_become: true
network_name: "metricspace.net"
kerberos_realm: "METRICSPACE.NET"
primary_kdc: "kdc.{{ network_name }}"
ldap_base_dn: "dc=metricspace,dc=net"
ldap_users_dn: "ou=people,{{ ldap_base_dn }}"
ldap_groups_dn: "ou=groups,{{ ldap_base_dn }}"
ldap_hosts_dn: "ou=hosts,{{ ldap_base_dn }}"
ldap_server_uri: "ldaps://ldap.{{ network_name }}"
nslcd_principal: "nss/{{ ansible_fqdn }}@{{ kerberos_realm }}"
slapd_principal: "ldap/{{ ansible_fqdn }}@{{ kerberos_realm }}"
