---
ansible_become: true
network_name: "example.com"
kerberos_realm: "EXAMPLE.COM"
primary_kdc: "kdc.{{ network_name }}"
ldap_base_dn: "dc=example,dc=com"
ldap_users_dn: "ou=people,{{ ldap_base_dn }}"
ldap_groups_dn: "ou=groups,{{ ldap_base_dn }}"
ldap_hosts_dn: "ou=hosts,{{ ldap_base_dn }}"
ldap_server_name: "ldap.{{ network_name }}"
ldap_server_uri: "ldaps://{{ ldap_server_name }}"
nslcd_principal: "nss/{{ ansible_fqdn }}@{{ kerberos_realm }}"
slapd_principal: "ldap/{{ ansible_fqdn }}@{{ kerberos_realm }}"
build_master: "build-master.{{ network_name }}"
