---
tomcat_conf_dir: "{{ tomcat_base_dir }}/conf"
tomcat_login_conf_file: "login.conf"
tomcat_login_conf_template: "{{ tomcat_login_conf_file }}.j2"
tomcat_login_conf: "{{ tomcat_conf_dir }}/{{ tomcat_login_conf_file }}"
tomcat_server_xml_file: "server.xml"
tomcat_server_xml_template: "{{ tomcat_server_xml_file }}.j2"
tomcat_server_xml: "{{ tomcat_conf_dir }}/{{ tomcat_server_xml_file }}"
tomcat_context_xml_file: "context.xml"
tomcat_context_xml: "{{ tomcat_conf_dir }}/{{ tomcat_context_xml_file }}"
tomcat_keytab: "{{ keytabs_dir }}/tomcat.keytab"
tomcat_keystore_file: "tomcat.p12"
tomcat_keystore: "{{ ssl_keystores_dir }}/{{ tomcat_keystore_file }}"
tomcat_keystore_password: "changeit"
tomcat_java_opts: "-Djava.security.auth.login.config={{ tomcat_login_conf_path }} -Djavax.net.ssl.keyStore={{ tomcat_keystore }} -Djavax.net.ssl.keyStorePassword={{ tomcat_keystore_password }} -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.trustStore={{ ssl_ca_keystore }} -Djavax.net.ssl.trustStorePassword={{ ssl_ca_keystore_password }} -Djava.awt.headless=true -server -Xmx1536m -Xms1536m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:+DisableExplicitGC"