- name: Install krb5.conf file
  template:
    src=krb5.conf.j2
    dest="{{ krb5_conf }}"
    owner=root
    group=wheel
    mode=644

- name: Install system PAM configuration
  copy:
    src=system.pam
    dest="{{ pam_dir }}/{{ item }}"
    owner=root
    group=wheel
    mode=644
  with_items:
    - system
    - other

- name: Install su PAM configuration
  copy:
    src=su.pam
    dest="{{ pam_dir }}/su"
    owner=root
    group=wheel
    mode=644

