# Ensure that privoxy user and group exist

- name: Create prioxy group
  group:
    name="{{ privoxy_group }}"
    gid=201
  tags:
    - setup

- name: Create privoxy user
  user:
    name="{{ privoxy_user }}"
    group="{{ privoxy_group }}"
    comment="Privoxy proxy user"
    uid=201
    home="{{ nonexistent_home }}"
    shell="{{ nologin_class }}"
    system=yes
  tags:
    - setup

# Set up the config files

- name: Create config file
  template:
    src=config.j2
    dest="{{ privoxy_config }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

# Enable privoxy in rc.conf and ensure the daemon is running.

- name: Enable privoxy in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^privoxy_enable="
    line="privoxy_enable=YES"
  tags:
    - setup

- name: Ensure privoxy is running
  service:
    name=privoxy
    state=started

- name: Restart privoxy
  service:
    name=privoxy
    state=restarted
  tags:
    - config
