;# Ensure that www user and group exist

- name: Create www group
  group:
    name="{{ www_group }}"
    gid=80
  tags:
    - setup

- name: Create www user
  user:
    name="{{ www_user }}"
    uid=80
    group="{{ www_group }}"
    comment="Dovecot user"
    home="{{ nonexistent_home }}"
    login_class="daemon"
    shell="{{ nologin_class }}"
    system=yes
  tags:
    - setup

# Copy certificates and keys into place

- name: Install https certificate
  copy:
    src="/etc/ssl/CA/certs/{{ letsencrypt_cert_filename }}"
    dest="{{ www_cert }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - setup
    - ssl

- name: Install https key
  copy:
    src="/etc/ssl/CA/private/{{ letsencrypt_key_filename }}"
    dest="{{ www_key }}"
    owner=root
    group="{{ www_group }}"
    mode=640
  tags:
    - setup
    - ssl

- name: Check https keytab
  file:
    path="{{ www_keytab }}"
    owner=root
    group="{{ www_group }}"
    mode=640
  tags:
    - setup

# Set up the dovecot.conf and dovecot-ldap.conf files

- name: Create httpd.conf file
  template:
    src=httpd.conf.j2
    dest="{{ www_config }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

# Enable apache is enabled in rc.conf and ensure the daemon is running.

- name: Enable apache in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^apache_enable="
    line="apache_enable=YES"
  tags:
    - setup

- name: Ensure apache is running
  service:
    name=apache
    state=started

- name: Restart apache
  service:
    name=apache
    state=restart
  tags:
    - config
    - ssl
