# Ensure that maia user and group exist

- name: Create maia group
  group:
    name="{{ maia_group }}"
    gid=110

- name: Create maia user
  user:
    name="{{ maia_user }}"
    uid=110
    group="{{ maia_group }}"
    comment="Scanning Virus Account"
    home="{{ maia_homedir }}"
    login_class="daemon"
    shell="/bin/sh"
    system=yes

# Copy certificates and keys into place

- name: Install postgres client certificate
  copy:
    src="/etc/ssl/CA/certs/{{ maia_postgres_cert_filename }}"
    dest="{{ maia_postgres_cert }}"
    owner=root
    group=wheel
    mode=644

- name: Install postgres client key
  copy:
    src="/etc/ssl/CA/private/{{ maia_postgres_key_filename }}"
    dest="{{ maia_postgres_key }}"
    owner=root
    group="{{ maia_group }}"
    mode=640

- name: Check dovecot keytab
  file:
    path="{{ dovecot_keytab }}"
    owner=root
    group="{{ dovecot_group }}"
    mode=640

# Set up the dovecot.conf and dovecot-ldap.conf files

- name: Create dovecot-ldap.conf file
  template:
    src=dovecot-ldap.conf.j2
    dest="{{ dovecot_ldap_config }}"
    owner=root
    group=wheel
    mode=644

- name: Create dovecot.conf file
  template:
    src=dovecot.conf.j2
    dest="{{ dovecot_config }}"
    owner=root
    group=wheel
    mode=644

# Set up a cron job to periodically refresh the dovecot user's
# Kerberos credentials

- name: Add cron job to refresh nslcd user's credentials
  cron:
    name="Refresh dovecot Kerberos credentials"
    minute="0"
    hour="*/6"
    user="{{ dovecot_user }}"
    job="{{ kinit }} -k -t {{ dovecot_keytab }} {{ dovecot_principal }}"

# Install a PAM configuration file identical to that of system for IMAP

- name: Install IMAP PAM configuration
  copy:
    src=imap.pam
    dest="{{ pam_dir }}/imap"
    owner=root
    group=wheel
    mode=644

# Enable dovecot is enabled in rc.conf and ensure the daemon is running.

- name: Enable dovecot in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^dovecot_enable="
    line="dovecot_enable=YES"

- name: Ensure dovecot is running
  service:
    name=dovecot
    state=started
