# Ensure that maia and clamav user and group exist

- name: Create clamav group
  group:
    name="{{ clamav_group }}"
    gid=106
  tags:
    - setup

- name: Create clamav user
  user:
    name="{{ clamav_user }}"
    uid=106
    group="{{ clamav_group }}"
    groups="{{ mail_group }}"
    comment="Clamav Antivirus"
    home="{{ nonexistent_home }}"
    login_class="daemon"
    shell="{{ nologin_class }}"
    system=yes
  tags:
    - setup

- name: Create maia group
  group:
    name="{{ maia_group }}"
    gid=110
  tags:
    - setup

- name: Create maia user
  user:
    name="{{ maia_user }}"
    uid=110
    group="{{ maia_group }}"
    groups="{{ clamav_group }},{{ mail_group }}"
    comment="Scanning Virus Account"
    home="{{ maia_homedir }}"
    login_class="daemon"
    shell="/bin/sh"
    system=yes
  tags:
    - setup

# Copy certificates and keys into place

- name: Install postgres client certificate
  copy:
    src="/etc/ssl/CA/certs/{{ maia_postgres_cert_filename }}"
    dest="{{ maia_postgres_cert }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - setup
    - ssl

- name: Install postgres client key
  copy:
    src="/etc/ssl/CA/private/{{ maia_postgres_key_filename }}"
    dest="{{ maia_postgres_key }}"
    owner=root
    group="{{ maia_group }}"
    mode=640
  tags:
    - setup
    - ssl

- name: Check dovecot keytab
  file:
    path="{{ dovecot_keytab }}"
    owner=root
    group="{{ dovecot_group }}"
    mode=640
  tags:
    - setup

# Set up the dovecot.conf and dovecot-ldap.conf files

- name: Create maia.conf file
  template:
    src=maia.conf.j2
    dest="{{ maia_config_dir }}/maia.conf"
    owner=root
    group=wheel
    mode=644
  tags:
    - setup
    - config

- name: Create maiad.conf file
  template:
    src=maiad.conf.j2
    dest="{{ maia_config_dir }}/maiad.conf"
    owner=root
    group=wheel
    mode=644
  tags:
    - setup
    - config

# Set up a cron job to periodically refresh the dovecot user's
# Kerberos credentials

- name: Add cron job to refresh maiad user's credentials
  cron:
    name="Refresh maia Kerberos credentials"
    minute="0"
    hour="*/6"
    user="{{ dovecot_user }}"
    job="{{ kinit }} -k -t {{ maia_keytab }} {{ maia_principal }}"
  tags:
    - setup

# Enable maiad is enabled in rc.conf and ensure the daemon is running.

- name: Enable maiad in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^maiad_enable="
    line="maiad_enable=YES"
  tags:
    - setup

- name: Enable clamav-freshclam in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^clamav_freshclam_enable="
    line="clamav_freshclam_enable=YES"
  tags:
    - setup

- name: Enable clamav-clamd in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^clamav_clamd_enable="
    line="clamav_clamd_enable=YES"
  tags:
    - setup

- name: Ensure maiad is running
  service:
    name=maiad
    state=started

- name: Restart maiad
  service:
    name=maiad
    state=restarted
  tags:
    - ssl
    - config

- name: Ensure clamav-freshclam is running
  service:
    name=clamav-freshclam
    state=started

- name: Restart clamav-freshclam
  service:
    name=clamav-freshclam
    state=restarted
  tags:
    - ssl
    - config

- name: Ensure clamav-clamd is running
  service:
    name=clamav-clamd
    state=started

- name: Restart clamav-clamd
  service:
    name=clamav-clamd
    state=restarted
  tags:
    - ssl
    - config
