# Have all builds use the -march=native option for building everything.

- name: Configure for local CPU optimizations
  lineinfile:
    dest=/etc/make.conf
    regexp="^CPUTYPE\?="
    line="CPUTYPE?=native"

# Set up port builds to use LibreSSL instead of OpenSSL.  LibreSSL has a better
# track record in terms of security, and it provides some better crypto options
# like the chacha20/poly1305 cipher.

- name: Configure ports to use LibreSSL
  lineinfile:
    dest=/etc/make.conf
    regexp="^DEFAULT_VERSIONS\+="
    line="DEFAULT_VERSIONS+=ssl=libressl"

- name: Set legacy WITH_OPENSSL_PORT option
  lineinfile:
    dest=/etc/make.conf
    regexp="^WITH_OPENSSL_PORT="
    line="WITH_OPENSSL_PORT=yes"

- name: Set legacy OPENSSL_PORT option
  lineinfile:
    dest=/etc/make.conf
    regexp="^OPENSSL_PORT="
    line="OPENSSL_PORT=security/libressl"

# Disable some useless components in src.conf.  This somewhat shortens
# buildworld by removing a bunch of junk that we never end up using.

- name: Disable some components in src.conf
  lineinfile:
    dest=/etc/src.conf
    regexp="^{{ item }}="
    line="{{ item }}=1"
  with_items:
    - WITHOUT_ATM
    - WITHOUT_AUTHPF
    - WITHOUT_BSNMP
    - WITHOUT_FLOPPY
    - WITHOUT_GAMES
    - WITHOUT_GPIB
    - WITHOUT_HAST
    - WITHOUT_IPX
    - WITHOUT_IPFILTER
    - WITHOUT_IPFW
    - WITHOUT_NCP
    - WITHOUT_NIS
    - WITHOUT_OFED
    - WITHOUT_PPP
    - WITHOUT_PMC
    - WITHOUT_RCMDS
    - WITHOUT_TALK
    - WITHOUT_TELNET
    - WITHOUT_VI
