# Ensure that ldap user and group exist

- name: Create ldap group
  group:
    name=ldap
    gid=398

- name: Create ldap user
  user:
    name=ldap
    uid=398
    group=ldap
    comment="OpenLDAP daemon"
    home="{{ nonexistent_home }}"
    login_class="daemon"
    shell="{{ nologin_class }}"
    system=yes

# Copy certificate and key into place

- name: Install ldap client certificate
  copy:
    src="/etc/ssl/CA/certs/{{ slapd_cert_filename }}"
    dest="{{ slapd_cert }}"
    owner=root
    group=wheel
    mode=644

- name: Install ldap client key
  copy:
    src="/etc/ssl/CA/private/{{ slapd_key_filename }}"
    dest="{{ slapd_key }}"
    owner=root
    group=nslcd
    mode=640

- name: Check slapd keytab
  file:
    path="{{ slapd_keytab }}"
    owner=root
    group=ldap
    mode=640

# Set up the nslcd configuration file and nsswitch.conf files.

#- name: Create nslcd.conf file
#  template:
#    src=nslcd.conf.j2
#    dest="{{ nslcd_config }}"
#    owner=root
#    group=wheel
#    mode=644

#- name: Add nsswitch.conf entries
#  lineinfile:
#    dest={{ nsswitch_conf }}
#    regexp="^{{ item }}{{ ":" }}"
#    line="{{ item }}{{ ":" }} ldap files"
#  with_items:
#    - passwd
#    - group

# Set up a cron job to periodically refresh the nslcd user's
# Kerberos credentials

- name: Add cron job to refresh ldap user's credentials
  cron:
    name="Refresh nslcd Kerberos credentials"
    minute="0"
    hour="*/6"
    user="ldap"
    job="{{ kinit }} -k -t {{ slapd_keytab }} {{ slapd_principal }}"

# Enable nslcd in LDAP and ensure the daemon is running.

#- name: Enable nslcd in rc.conf
#  lineinfile:
#    dest="{{ rc_conf }}"
#    regexp="^nslcd_enable="
#    line="nslcd_enable=YES"

#- name: Ensure ldap is running
#  service:
#    name=nslcd
#    state=started
