# Ensure that nslcd user and group exist

- name: Create nslcd group
  group:
    name="{{ nslcd_group }}"
    gid=928
  tags:
    - setup

- name: Create nslcd user
  user:
    name="{{ nslcd_user }}"
    uid=928
    group="{{ nslcd_group }}"
    comment="nslcd daemon"
    home="{{ nonexistent_home }}"
    login_class="daemon"
    shell="{{ nologin_class }}"
    system=yes
  tags:
    - setup

# Copy certificate and key into place

- name: Install nslcd client certificate
  copy:
    src="/etc/ssl/CA/certs/{{ nslcd_cert_filename }}"
    dest="{{ nslcd_cert }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - setup
    - ssl

- name: Install nslcd client key
  copy:
    src="/etc/ssl/CA/private/{{ nslcd_key_filename }}"
    dest="{{ nslcd_key }}"
    owner=root
    group="{{ nslcd_group }}"
    mode=640
  tags:
    - setup
    - ssl

- name: Check nslcd keytab
  file:
    path="{{ nslcd_keytab }}"
    owner=root
    group="{{ nslcd_group }}"
    mode=640
  tags:
    - setup

# Set up the nslcd configuration file and nsswitch.conf files.

- name: Create nslcd.conf file
  template:
    src=nslcd.conf.j2
    dest="{{ nslcd_config }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Add nsswitch.conf entries
  lineinfile:
    dest={{ nsswitch_conf }}
    regexp="^{{ item }}{{ ":" }}"
    line="{{ item }}{{ ":" }} ldap files"
  with_items:
    - passwd
    - group
  tags:
    - setup
    - config

# Set up a cron job to periodically refresh the nslcd user's
# Kerberos credentials

- name: Add cron job to refresh nslcd user's credentials
  cron:
    name="Refresh nslcd Kerberos credentials"
    minute="0"
    hour="*/6"
    user="{{ nslcd_user }}"
    job="{{ kinit }} -k -t {{ nslcd_keytab }} {{ nslcd_principal }}"
  tags:
    - setup

# Enable nslcd in LDAP and ensure the daemon is running.

- name: Enable nslcd in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^nslcd_enable="
    line="nslcd_enable=YES"
  tags:
    - setup

- name: Ensure nslcd is running
  service:
    name=nslcd
    state=started

- name: Restart nslcd
  service:
    name=nslcd
    state=restart
  tags:
    - config
    - ssl
