# Set up the config files

- name: Install public wiki hibernate config file
  template:
    src="{{ public_wiki_hibernate_template }}"
    dest="{{ public_wiki_hibernate_cfg }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Install private wiki hibernate config file
  template:
    src="{{ private_wiki_hibernate_template }}"
    dest="{{ private_wiki_hibernate_cfg }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Copying default cacerts keystore
  copy:
    src: "{{ postgres_jar_install }}"
    dest: "{{ tomcat_lib_dir }}/{{ postgres_jar }}"
    remote_src: yes
  tags:
    - setup

