# Set up the config files

- name: Install public wiki hibernate config file
  template:
    src="{{ public_wiki_hibernate_template }}"
    dest="{{ public_wiki_hibernate_cfg }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Install private wiki hibernate config file
  template:
    src="{{ private_wiki_hibernate_template }}"
    dest="{{ private_wiki_hibernate_cfg }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Copying postgresql JDBC driver jar
  copy:
    src: "{{ postgres_jar_install }}"
    dest: "{{ tomcat_lib_dir }}/{{ postgres_jar }}"
    remote_src: yes
  tags:
    - setup

- name: Copying private wiki cache config
  copy:
    src: "{{ cache_config_xml }}"
    dest: "{{ private_wiki_cache_config }}"
  tags:
    - setup
    - config

- name: Copying public wiki cache config
  copy:
    src: "{{ cache_config_xml }}"
    dest: "{{ public_wiki_cache_config }}"
  tags:
    - setup
    - config

