- name: Install jenkins context.xml file
  template:
    src="{{ jenkins_xml_template }}"
    dest="{{ jenkins_xml }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Install gpg directory
  unarchive:
    copy=true
    src="gpg.tar"
    dest="{{ tomcat_home_dir }}"
    owner="{{ tomcat_user }}"
    group="{{ tomcat_group }}"
    mode=700
  tags:
    - config
    - setup

- name: Install .gitconfig
  template:
    src="{{ jenkins_gitconfig_template }}"
    dest="{{ jenkins_gitconfig }}"
    owner="{{ tomcat_user }}"
    group="{{ tomcat_group }}"
    mode=644
  tags:
    - config
    - setup

- name: Install jenkins.war into webapps dir
  copy:
    src: "{{ jenkins_war_install }}"
    dest: "{{ jenkins_war_deploy }}"
    remote_src: yes
  tags:
    - config
    - setup
    - ssl
