# Ensure that tor user and group exist

- name: Create tor group
  group:
    name="{{ tor_group }}"
    gid=256
  tags:
    - setup

- name: Create tor user
  user:
    name="{{ tor_user }}"
    group="{{ tor_group }}"
    comment="Tor anonymizing router"
    uid=256
    home="{{ tor_data_dir }}"
    shell="{{ nologin_class }}"
    system=yes
  tags:
    - setup

# Set up the torrc files

- name: Create torrc file
  template:
    src=torrc.j2
    dest="{{ torrc }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config

# Enable tor in rc.conf and ensure the daemon is running.

- name: Enable tor in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^tor_enable="
    line="tor_enable=YES"
  tags:
    - setup

- name: Ensure tor is running
  service:
    name=tor
    state=started

- name: Restart tor
  service:
    name=tor
    state=restarted
  tags:
    - config
