# Ensure that ldap user and group exist

- name: Create ldap group
  group:
    name="{{ slapd_group }}"
    gid=389

- name: Create ldap user
  user:
    name="{{ slapd_user }}"
    uid=389
    group="{{ slapd_group }}"
    groups="{{ sasl_group }}"
    comment="OpenLDAP daemon"
    home="{{ nonexistent_home }}"
    login_class="daemon"
    shell="{{ nologin_class }}"
    system=yes

# Copy certificate and key into place

- name: Install ldap client certificate
  copy:
    src="/etc/ssl/CA/certs/{{ slapd_cert_filename }}"
    dest="{{ slapd_cert }}"
    owner=root
    group=wheel
    mode=644

- name: Install ldap client key
  copy:
    src="/etc/ssl/CA/private/{{ slapd_key_filename }}"
    dest="{{ slapd_key }}"
    owner=root
    group="{{ slapd_group }}"
    mode=640

- name: Check slapd keytab
  file:
    path="{{ slapd_keytab }}"
    owner=root
    group="{{ slapd_group }}"
    mode=640

# Set up the slapd SASL config file.  This tells SASL to use saslauthd, where to
# find the keytab, and where to find the mux.

- name: Install sasl slapd.conf
  template:
    src=sasl2.slapd.conf.j2
    dest="{{ slapd_sasl_file }}"
    owner=root
    group=wheel
    mode=644

# Set up the slapd.conf and slapd.access files

- name: Create slapd.access file
  template:
    src=slapd.access.j2
    dest="{{ slapd_access }}"
    owner=root
    group=wheel
    mode=644

- name: Create slapd.conf file
  template:
    src=slapd.conf.j2
    dest="{{ slapd_config }}"
    owner=root
    group=wheel
    mode=644

# Enable slapd is enabled in rc.conf and ensure the daemon is running.

- name: Enable slapd in rc.conf
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^slapd_enable="
    line="slapd_enable=YES"

- name: Set slapd kerberos keytab
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^slapd_krb5_ktname"
    line="slapd_krb5_ktname={{ slapd_keytab }}"

- name: Set slapd flags
  lineinfile:
    dest="{{ rc_conf }}"
    regexp="^slapd_flags="
    line="slapd_flags=\"-h 'ldapi:/// ldap:/// ldaps:///'\""

- name: Ensure slapd is running
  service:
    name=slapd
    state=started
