- name: Install artifactory context.xml file
  template:
    src="{{ artifactory_xml_template }}"
    dest="{{ artifactory_xml }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Install derby JAR into tomcat lib dir
  copy:
    src: "{{ artifactory_install_derby_jar }}"
    dest: "{{ artifactory_deploy_derby_jar }}"
    remote_src: yes
  tags:
    - config
    - setup

- name: Install artifactory.war into webapps dir
  copy:
    src: "{{ artifactory_install_war }}"
    dest: "{{ artifactory_deploy_war }}"
    remote_src: yes
  tags:
    - config
    - setup

