- name: Install artifactory context.xml file
  template:
    src="{{ artifactory_xml_template }}"
    dest="{{ artifactory_xml }}"
    owner=root
    group=wheel
    mode=644
  tags:
    - config
    - setup

- name: Install artifactory.war into webapps dir
  copy:
    src: "{{ artifactory_war_install }}"
    dest: "{{ artifactory_war_deploy }}"
    remote_src: yes
  tags:
    - config
    - setup

